apiVersion: v1
kind: ConfigMap

metadata:
  name: production-app-config
  namespace: production

data:
  NODE_ENV: "production"
  APP_NAME: "AWS Production 3-Tier DevOps Project"
  APP_PORT: "3000"
  LOG_LEVEL: "info"